name: CI Fast Splash

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  flutter:

    name: Validar Flutter

    runs-on: ubuntu-latest


    steps:

      - name: Baixar código do repositório
        uses: actions/checkout@v4


      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable


      - name: Instalar dependências
        run: flutter pub get


      - name: Analisar código Flutter
        run: flutter analyze


  web-java:

    name: Validar Web Java

    runs-on: ubuntu-latest


    steps:

      - name: Baixar código do repositório
        uses: actions/checkout@v4


      - name: Construir aplicação Web
        run: docker build -t fast-splash-web ./web/FastSplashWeb